name: Test and Build Package

on: 
  push:
    branches:
      - master
    tags: 
      - v*

env:
  IMAGE_NAME: slack_file_manager/slack_file_manager

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: npm install --save-dev
    - name: Run Build Action
      run: npm run build
    - name: Run Tests
      run: npm run test
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Package
        run: npm install --save-dev && npm run build
      - name: Login to Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
