name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: npm install --save-dev
    - name: Run Build Action
      run: npm run build
    - name: Run Tests
      run: mocha
