name: Run Tests
on: 
  push:
    branches:
      - master
    tags: 
      - v*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Install
      run: npm install --save-dev
    - name: Run Build Action
      run: npm run build
    - name: Run Tests
      run: npm run test
